name: Automatisation des tests DevSecOps

on: push

jobs:
  # 1° Contrôle du fichier requirements.txt
  Dependances:
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Contrôle du fichier requirements.txt
        run: |
          echo "Vérification du fichier requirements.txt ..."
          if [ ! -f requirements.txt ]; then
            echo "Le fichier requirements.txt est manquant."
            exit 1
          fi
          echo "Le fichier requirements.txt est présent."
          echo "Test d’installation des dépendances..."
          pip install -r requirements.txt
          echo "Installation réussie, le fichier est valide."

  # 2° Contrôle du Dockerfile (uniquement si Dependances réussit)
  Dockerfile:
    runs-on: ubuntu-latest
    needs: Dependances
    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Vérification du Dockerfile
        run: |
          echo "Vérification du fichier Dockerfile ..."
          if [ ! -f Dockerfile ]; then
            echo "Le fichier Dockerfile est manquant."
            exit 1
          fi
          echo "Le fichier Dockerfile est présent."
          echo "Test de construction de l'image Docker..."
          docker build -t breakableflask-test .
          echo "Image Docker construite avec succès."

  # 3° Déploiement (simulation)
  Deploy:
    runs-on: ubuntu-latest
    needs: Dockerfile
    steps:
      - name: Déploiement
        run: |
          echo "Rien à faire ici. Votre application est prête à être déployée."
